#:kivy 2.2.1
<CustomLabelRoboto@MDLabel>: # Pre-made class to define default settings to subtitles labels with MDLabel
    font_name: "Roboto"
    font_size: "15dp" # 15sp for text
    halign: "center"
    pos_hint: {"center_x": 0.5, "center_y": 0.5,"top": 0}
    theme_text_color: "Custom"
    text_color: app.colors["White"]

    
<CustomLabelAD@MDLabel>: # Pre-made class to define default settings to subtitles labels with MDLabel
    font_name: "ADLaMDisplay-Regular.ttf"
    font_size: "30sp" # 30sp for titles
    halign: "center"
    pos_hint: {"center_x": 0.5, "center_y": 0.5,"top": 0}
    theme_text_color: "Custom"
    text_color: app.colors["White"]

WindowManager:
    MainWindow:
    SecundaryWindow:

<MainWindow>:
    name: "Main Window"

    BoxLayout:
        orientation: 'vertical'

        MDTopAppBar:
            #Cambios en la top bar
            md_bg_color: app.colors["Black"]
            left_action_items: [['PossibleLogoW.png',lambda x: None]]
            title: "ExoBoost"
            font_name: 'ADLaMDisplay-Regular.ttf'
            pos_hint: {'center_x':0.5,'center_y':0.5}                              

        MDBottomNavigation:
            id: bottom_nav
            # selected_color_background: app.colors["Light Orange"]
            panel_color: app.colors["Black"]

            # Set active/normal colors
            text_color_normal: app.colors["Cyan"]
            text_color_active: app.colors["Light Orange"]
            icon_color_normal: app.colors["Cyan"]
            icon_color_active: app.colors["Light Orange"]

            MDBottomNavigationItem:
                # Bluetooth settings tab 
                id: bluetooh_tab
                name: "Bluetooth settings"
                text: "Bluetooth settings"
                icon: "bluetooth-settings"

                # Actions for the button
                on_tab_release:
                    print("tab release")

                # Tab design
                BoxLayout:
                    orientation: 'vertical'
                    # Background color
                    canvas.before:
                        Color:
                            rgba: app.colors["Dark Blue"]
                        Rectangle:
                            pos: self.pos
                            size: self.size

                    # Elements on app
# -------------------- Menu Bluetooth --------------------------
                    CustomLabelAD:
                        id: bluetooth_title
                        text: "Bluetooth Connection"

                    # Boton para buscar dispositivos                       
                    BoxLayout:
                        Widget:
                        MDFillRoundFlatButton:
                            id: bluetooth_device_search
                            text: 'Search Devices'
                            text_color: app.colors['White']
                            size_hint: None, None
                            size: '200dp','50dp'
                            ripple_effect: False
                            ripple_color: app.colors['Cyan']
                            on_press: self.md_bg_color = app.colors["Light Orange"]
                            on_release: self.md_bg_color = app.colors["Cyan"]
                            on_press: root.search_devices()
                            md_bg_color: app.colors["Cyan"]
                            pos_hint: {'center_x':0.5,'center_y':0.5}
                            height: root.height*0.065
                        Widget:
                    # Design choice para espacio entre elementos :)
                    Widget:
                        size_hint_y: None
                        height: '20dp'
                    # Menu con dispositivos disponibles
                    ScrollView:
                        size_hint: (1,1)
                        RecycleView:
                            id: device_list
                            viewclass: 'SelectableLabel'
                            RecycleBoxLayout:
                                #color: app.colors["White"]
                                default_size: None, dp(56)
                                default_size_hint: 1,None
                                size_hint_y: None
                                height: self.minimum_height
                                orientation: 'vertical'
                    # Botón para conectarse/desconectarse a un dispositivo
                    BoxLayout:
                        size_hint_y: None
                        height: '50 dp'
                        Widget:
                        MDFillRoundFlatButton:
                            id: bluetooth_connect
                            text: 'CONNECT/DISCONNECT'
                            text_color: app.colors['White']
                            size_hint: None, None
                            ripple_effect: False
                            ripple_color: app.colors['Cyan']
                            on_press: self.md_bg_color = app.colors["Light Orange"]
                            on_release: self.md_bg_color = app.colors["Cyan"]
                            width: root.width*0.5
                            height: root.height*0.065
                            #on_press: 
                            try:
                                root.connect_disconnect()
                            except:
                                print('error')
                            md_bg_color: app.colors["Cyan"]
                            pos_hint: {'center_x':0}
                        Widget:
                    #Esto es solo para crear un espacio abajo (design choice)
                    Widget:
                        size_hint_y: None
                        height: '48dp'
# ------------------------ Otros Menus -----------------------------
            MDBottomNavigationItem:
                id: assistance_tab
                name: "Assistance mode"
                text: "Assistance mode"
                icon: "walk"

                on_tab_release:
                    print("tab release")

                MDLabel:
                    text: "Assistance Mode"
                    halign: "center"

            MDBottomNavigationItem:
                id: tuninig_tab
                name: "Tuning mode"
                text: "Tuning mode"
                icon: "equalizer"

                # Actions
                on_tab_release:
                    print("tab release")

                on_tab_press:
                    print("on_tab_press")

                MDLabel:
                    text: "Tuning Mode"
                    halign: "center"

<SecundaryWindow>:
    # Empty
    name: "Secundary Window"
# Estas son funciones para dar formato a la lista de dispositivos
# Aqui se le da formato al texto del menú de dispositivos
<SelectableLabel@MDLabel>:
    size_hint_y: None
    height: self.texture_size[1]
    halign: 'center'
    valign: 'middle'
    theme_text_color: 'Custom'
    text_color: app.colors['White']
    on_touch_down:
        self.parent.parent.parent.select_with_touch(self.index, 'down')
#Aqui se le da formato a la caja que contiene dicho menú :)
<SelectableRecycleBoxLayout@RecycleBoxLayout>:
    default_size: None, dp(56)
    default_size_hint: 1, None
    size_hint_y: None
    height: self.minimum_height
    orientation: 'vertical'
    