#:kivy 2.2.1

WindowManager:
    MainWindow:
    SecundaryWindow:

<CustomLabel>: # Pre-made class to define default settings to subtitles labels with MDLabel
    font_name: "Roboto"
    font_size: "15sp" # 30sp for titles
    halign: "center"
    pos_hint: {"center_x": 0.5, "top": 0}
    theme_text_color: "Custom"
    text_color: app.colors["White"]

<CustomTextEntry>: # Pre-made class to define defaultl settings to entry text boxes
    helper_text_mode: "on_focus"
    hint_text_color_normal: app.colors["Black"]  # White when not focused
    hint_text_color_focus: app.colors["Light Orange"]   # Orange when focused
    pos_hint: {"center_x": 0.5, "center_y": 0.5}  # Center the TextEntry horizontally and vertically

    hint_text: "Fill mode"
    mode: "fill"
    fill_color: app.colors["White"]

<MainWindow>:
    name: "Main Window"

    BoxLayout:
        orientation: 'vertical'
        halign: "center"
        valign: "center"
        pos_hint: {"center_y": 0.5, "center_x": 0.5}

        MDTopAppBar:
            title: "ExoBoost"
            md_bg_color: app.colors["Black"]
            font_name: 'ADLaMDisplay-Regular.ttf'
            Image:
                source: 'PossibleLogoW.png'
                size: self.texture_size
                  

        MDBottomNavigation:
            id: bottom_nav
            # selected_color_background: app.colors["Light Orange"] # Check how to change background color
            panel_color: app.colors["Black"]

            # Set active/normal colors
            text_color_normal: app.colors["Cyan"]
            text_color_active: app.colors["Light Orange"]
            icon_color_normal: app.colors["Cyan"]
            icon_color_active: app.colors["Light Orange"]

            MDBottomNavigationItem:
                # Bluetooth settings tab 
                id: bluetooh_tab
                name: "Bluetooth settings"
                text: "Bluetooth settings"
                icon: "bluetooth-settings"

                # Actions for the button
                on_tab_release:
                    print("tab release")

                # Tab design
                BoxLayout:
                    orientation: 'vertical'
                    # Background color
                    canvas.before:
                        Color:
                            rgba: app.colors["Dark Blue"]
                        Rectangle:
                            pos: self.pos
                            size: self.size

                    # Elements on app
# -------------------- Menu Bluetooth --------------------------
                    MDLabel:
                        id: bluetooth_title
                        text: "Bluetooth Connection"
                        font_name: 'ADLaMDisplay-Regular.ttf'
                        font_size: "25sp"
                        halign: "center"
                        size_hint_y: 0.5
                        height: self.texture_size[1]
                        theme_text_color: "Custom"
                        text_color: app.colors["White"]
                    # Boton para buscar dispositivos                       
                    BoxLayout:
                        Widget:
                        MDFillRoundFlatButton:
                            id: bluetooth_device_search
                            text: 'Search Devices'
                            text_color: app.colors['White']
                            size_hint: None, None
                            size: '200dp','50dp'
                            ripple_effect: False
                            ripple_color: app.colors['Cyan']
                            on_press: self.md_bg_color = app.colors["Light Orange"]
                            on_release: self.md_bg_color = app.colors["Cyan"]
                            on_press: root.search_devices()
                            md_bg_color: app.colors["Cyan"]
                            pos_hint: {'center_x':0.5,'center_y':0.5}
                        Widget:
                    # Design choice para espacio entre elementos :)
                    Widget:
                        size_hint_y: None
                        height: '20dp'
                    # Menu con dispositivos disponibles
                    ScrollView:
                        size_hint: (1,1)
                        RecycleView:
                            id: device_list
                            viewclass: 'SelectableLabel'
                            RecycleBoxLayout:
                                #color: app.colors["White"]
                                default_size: None, dp(56)
                                default_size_hint: 1,None
                                size_hint_y: None
                                height: self.minimum_height
                                orientation: 'vertical'
                    # Botón para conectarse/desconectarse a un dispositivo
                    BoxLayout:
                        size_hint_y: None
                        height: '50 dp'
                        Widget:
                        MDFillRoundFlatButton:
                            id: bluetooth_connect
                            text: 'CONNECT/DISCONNECT'
                            text_color: app.colors['White']
                            size_hint: None, None
                            ripple_effect: False
                            ripple_color: app.colors['Cyan']
                            on_press: self.md_bg_color = app.colors["Light Orange"]
                            on_release: self.md_bg_color = app.colors["Cyan"]
                            on_press: root.connect_disconnect()
                            md_bg_color: app.colors["Cyan"]
                            pos_hint: {'center_x':0}
                        Widget:
                    #Esto es solo para crear un espacio abajo (design choice)
                    Widget:
                        size_hint_y: None
                        height: '48dp'
# ------------------------ Otros Menus -----------------------------
            MDBottomNavigationItem:
                id: assistance_tab
                name: "Assistance mode"
                text: "Assistance mode"
                icon: "walk"

                on_tab_release:
                    print("tab release")

                MDLabel:
                    text: "Assistance Mode"
                    halign: "center"

            MDBottomNavigationItem: # TUNING TAB
                id: tuning_tab
                name: "Tuning mode"
                text: "Tuning mode"
                icon: "equalizer"

                # Actions
                on_tab_release:
                    print("tab release")

                # Elements
                FloatLayout:
                    orientation: "vertical"
                    # size_hint_y: None
                    # size_hint_x: None
                    pos_hint: {"center_y": 0.5, "center_x": 0.5}
                    halign: "center"
                    valign: "center"

                    canvas.before:
                        Color:
                            rgba: app.colors["Dark Blue"]
                        Rectangle:
                            pos: self.pos
                            size: self.size

                    GridLayout:
                        rows: 5
                        cols: 1
                        padding: 30, 10
                        spacing: 10

                        CustomLabel: # ROW 1 
                            id: tuning_label
                            text: "Tuning Mode"
                            font_size: "30sp"
                            size: self.width, 10
                            canvas.before:
                                Color:
                                    rgba: app.colors["Dark Blue"]
                                Rectangle:
                                    pos: self.pos
                                    size: self.size

                        FloatLayout: # ROW 2
                            orientation: "vertical"
                            size: self.width, 10
                            pos_hint: {"center_x": 0.5, "center_y": 0.5}  # Center the BoxLayout horizontally
                            
                            Spinner:
                                id: limb_dropdown
                                orientation: "verical"
                                text: "Limb tuning"
                                pos_hint: {"center_x": 0.5, "center_y": 0.5}  # Center the Spinner horizontally

                                # Option values
                                values: ["Right leg", "Left leg", "Right arm", "Left arm"]
                                
                                # Customization
                                size_hint: None, None
                                size: 200, 44
                                background_color: app.colors["White"]
                                color: app.colors["White"]
                                
                                # Actions
                                on_text: app.limb_dropdown_clicked(limb_dropdown.text)

                        BoxLayout: #ROW 3 
                            orientation: "vertical"
                            padding: [10, 10, 10, 10]
                            spacing: 100
                            size: self.width, 90

                            CustomLabel: 
                                id: motor1_label
                                text: "Hip motor"

                            GridLayout:
                                rows: 1
                                cols: 3
                                padding: [10, 10, 10, 10]
                                spacing: 10

                                CustomTextEntry: # col 1
                                    id: kc_motor1
                                    hint_text: "Kc:"
                                    on_text_validate:
                                        app.on_entry_text(kc_motor1.text)
                                CustomTextEntry: # col 2
                                    id: ti_motor1
                                    hint_text: "Ti:"
                                    on_text_validate:
                                        app.on_entry_text(ti_motor1.text)

                                CustomTextEntry: # col 3
                                    id: sp_motor1
                                    hint_text: "SP:"
                                    on_text_validate:
                                        app.on_entry_text(sp_motor1.text)


                            BoxLayout:
                                orientation: "vertical"
                                size_hint: None, None
                                size: 150, 50
                                pos_hint: {"center_x": 0.5, "center_y": 0.5}
                                CustomTextEntry:
                                    id: pv_motor1
                                    hint_text: "PV:"
                                    on_text_validate:
                                        app.on_entry_text(pv_motor1.text)
                        
                        BoxLayout: #ROW 3 
                            orientation: "vertical"
                            padding: [10, 10, 10, 10]
                            spacing: 100
                            size: self.width, 90

                            CustomLabel: 
                                id: motor1_label
                                text: "Hip motor"

                            GridLayout:
                                rows: 1
                                cols: 3
                                padding: [10, 10, 10, 10]
                                spacing: 10

                                CustomTextEntry: # col 1
                                    id: kc_motor3
                                    hint_text: "Kc:"
                                    on_text_validate:
                                        app.on_entry_text(kc_motor1.text)
                                CustomTextEntry: # col 2
                                    id: ti_motor3
                                    hint_text: "Ti:"
                                    on_text_validate:
                                        app.on_entry_text(ti_motor1.text)

                                CustomTextEntry: # col 3
                                    id: sp_motor3
                                    hint_text: "SP:"
                                    on_text_validate:
                                        app.on_entry_text(sp_motor1.text)


                            BoxLayout:
                                orientation: "vertical"
                                size_hint: None, None
                                size: 150, 50
                                pos_hint: {"center_x": 0.5, "center_y": 0.5}
                                CustomTextEntry:
                                    id: pv_motor3
                                    hint_text: "PV:"
                                    on_text_validate:
                                        app.on_entry_text(pv_motor1.text)

                        BoxLayout: #ROW 3 
                            orientation: "vertical"
                            padding: [10, 10, 10, 10]
                            spacing: 100
                            size: self.width, 90

                            CustomLabel: 
                                id: motor2_label
                                text: "Hip motor"

                            GridLayout:
                                rows: 1
                                cols: 3
                                padding: [10, 10, 10, 10]
                                spacing: 10

                                CustomTextEntry: # col 1
                                    id: kc_motor2
                                    hint_text: "Kc:"
                                    on_text_validate:
                                        app.on_entry_text(kc_motor1.text)
                                CustomTextEntry: # col 2
                                    id: ti_motor2
                                    hint_text: "Ti:"
                                    on_text_validate:
                                        app.on_entry_text(ti_motor1.text)

                                CustomTextEntry: # col 3
                                    id: sp_motor2
                                    hint_text: "SP:"
                                    on_text_validate:
                                        app.on_entry_text(sp_motor1.text)


                            BoxLayout:
                                orientation: "vertical"
                                size_hint: None, None
                                size: 150, 50
                                pos_hint: {"center_x": 0.5, "center_y": 0.5}
                                CustomTextEntry:
                                    id: pv_motor2
                                    hint_text: "PV:"
                                    on_text_validate:
                                        app.on_entry_text(pv_motor1.text)

<SecundaryWindow>:
    # Empty
    name: "Secundary Window"
# Estas son funciones para dar formato a la lista de dispositivos
# Aqui se le da formato al texto del menú de dispositivos
<SelectableLabel@MDLabel>:
    size_hint_y: None
    height: self.texture_size[1]
    halign: 'center'
    valign: 'middle'
    theme_text_color: 'Custom'
    text_color: app.colors['White']
    on_touch_down:
        self.parent.parent.parent.select_with_touch(self.index, 'down')
#Aqui se le da formato a la caja que contiene dicho menú :)
<SelectableRecycleBoxLayout@RecycleBoxLayout>:
    default_size: None, dp(56)
    default_size_hint: 1, None
    size_hint_y: None
    height: self.minimum_height
    orientation: 'vertical'
    